### ISSUE TITLE
Id Required Issues on Orders Page 

### ISSUE THREAD

**Issue by kanthikiran1988** [taxjar/taxjar-magento2-extension#85]
When I install the TaxJar extension I could not View Orders Page[Sales -> Orders].

Version: Magento 2.2.8
TaxJar Version: 1.2.0 [Which is available in Magento Marketplace]

Below is the developer trace:

```
2019-10-18T15:37:25+00:00 INFO (6): Exception: trace in /var/www/vhosts/httpdocs/vendor/magento/module-sales/Model/OrderRepository.php:133
Stack trace:
#0 /var/www/vhosts/httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\OrderRepository->get('0')
#1 /var/www/vhosts/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\OrderRepository\Interceptor->___callParent('get', Array)
#2 /var/www/vhosts/httpdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\OrderRepository\Interceptor->Magento\Framework\Interception\{closure}('0')
#3 /var/www/vhosts/httpdocs/generated/code/Magento/Sales/Model/OrderRepository/Interceptor.php(26): Magento\Sales\Model\OrderRepository\Interceptor->___callPlugins('get', Array, Array)
#4 /var/www/vhosts/httpdocs/app/code/Taxjar/SalesTax/Ui/Component/Listing/Column/SyncedOrder.php(74): Magento\Sales\Model\OrderRepository\Interceptor->get('0')
#5 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Element/UiComponent/Context.php(364): Taxjar\SalesTax\Ui\Component\Listing\Column\SyncedOrder->prepareDataSource(Array)
#6 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Element/UiComponent/Context.php(361): Magento\Framework\View\Element\UiComponent\Context->prepareDataSource(Array, Object(Taxjar\SalesTax\Ui\Component\Listing\Column\SyncedOrder))
#7 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Element/UiComponent/Context.php(361): Magento\Framework\View\Element\UiComponent\Context->prepareDataSource(Array, Object(Magento\Ui\Component\Listing\Columns))
#8 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Element/UiComponent/Context.php(228): Magento\Framework\View\Element\UiComponent\Context->prepareDataSource(Array, Object(Magento\Ui\Component\Listing))
#9 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout/Generic.php(75): Magento\Framework\View\Element\UiComponent\Context->getDataSourceData(Object(Magento\Ui\Component\Listing))
#10 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout/Generator/Structure.php(46): Magento\Framework\View\Layout\Generic->build(Object(Magento\Ui\Component\Listing))
#11 /var/www/vhosts/httpdocs/vendor/magento/module-ui/TemplateEngine/Xhtml/Result.php(94): Magento\Framework\View\Layout\Generator\Structure->generate(Object(Magento\Ui\Component\Listing))
#12 /var/www/vhosts/httpdocs/vendor/magento/module-ui/TemplateEngine/Xhtml/Result.php(116): Magento\Ui\TemplateEngine\Xhtml\Result->appendLayoutConfiguration()
#13 /var/www/vhosts/httpdocs/vendor/magento/module-ui/Component/Wrapper/UiComponent.php(73): Magento\Ui\TemplateEngine\Xhtml\Result->__toString()
#14 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Element/AbstractBlock.php(667): Magento\Ui\Component\Wrapper\UiComponent->_toHtml()
#15 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(570): Magento\Framework\View\Element\AbstractBlock->toHtml()
#16 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(531): Magento\Framework\View\Layout->_renderUiComponent('sales_order_gri...')
#17 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('sales_order_gri...')
#18 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('sales_order_gri...')
#19 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('sales_order_gri...', false)
#20 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('sales_order_gri...', false)
#21 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('content', false)
#22 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#23 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#24 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', false)
#25 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('content', false)
#26 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('main.col', false)
#27 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#28 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#29 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', false)
#30 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('main.col', false)
#31 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...', false)
#32 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#33 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#34 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', false)
#35 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...', false)
#36 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.main.conta...', false)
#37 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#38 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#39 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', false)
#40 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...', false)
#41 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.content', false)
#42 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#43 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#44 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', false)
#45 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.content', false)
#46 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#47 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#48 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#49 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#50 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false)
#51 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('backend.page', false)
#52 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#53 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#54 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', false)
#55 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page', false)
#56 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('root', false)
#57 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#58 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#59 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#60 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#61 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#62 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Result/Page.php(257): Magento\Framework\View\Layout\Interceptor->getOutput()
#63 /var/www/vhosts/httpdocs/vendor/magento/framework/View/Result/Layout.php(170): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#64 /var/www/vhosts/httpdocs/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#65 /var/www/vhosts/httpdocs/vendor/magento/framework/App/Http.php(140): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#66 /var/www/vhosts/httpdocs/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#67 /var/www/vhosts/httpdocs/vendor/magento/framework/App/Bootstrap.php(257): Magento\Framework\App\Http\Interceptor->launch()
#68 /var/www/vhosts/httpdocs/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#69 {main}
```

**Comment by ryanreeves-taxjar** [comment]
Hi @kanthikiran1988, we've released a new version of our extension to the Magento Marketplace which should address this issue.  If you continue to experience this error after updating, please email our support team (support@taxjar.com) and include a link to this issue.  Thanks!
